### ISSUE TITLE
Etiketleme aracını nasıl bulabilirim ?

### ISSUE THREAD

**Issue by tarkanoz** [cetinsamet/named-entity-recognition-turkish#1]
Merhaba,
Ner üzerinde çalışıyorum ama bu formata uygun etiketleme aracı bulamadım yardımcı olabilir misiniz,bu formatta etiketlemeyi nasıl yapabilirim ?

**Comment by cetinsamet** [comment]
Merhaba,
Dataset'i hazır olarak kullandım ve bildiğim kadarıyla uzun bir çalışma sonucu manuel olarak etiketlenmiş. Yalnızca _BIO-encoded_ etiketleri kendim oluşturdum. 

_BIO-encoded_ etiketleme sizin de tahmin edebileceğiniz gibi görece kolayca gerçekleştirilebilir. Ancak birincil etiketlemelerin, şimdilik, Türkçe için kolayca gerçekleştirilebileceğini tahmin etmiyorum. 

Kolaylıklar.

**Comment by tarkanoz** [comment]
Teşekkür ederim
